
    create table attendance (
        id bigint generated by default as identity,
        schedule_id bigint not null,
        timestamp timestamp(6) not null,
        user_id bigint not null,
        status varchar(255),
        primary key (id)
    );

    create table fingerprint (
        id bigint generated by default as identity,
        section_id bigint,
        user_id bigint,
        fingerprinturl varchar(255),
        primary key (id)
    );

    create table laboratory (
        capacity integer not null,
        id bigint generated by default as identity,
        name varchar(255),
        room_code varchar(255),
        primary key (id)
    );

    create table program (
        id bigint generated by default as identity,
        program_abbreviation varchar(255),
        program_description varchar(255),
        program_name varchar(255),
        primary key (id)
    );

    create table schedule_days (
        schedule_id bigint not null,
        recurrence_days varchar(255)
    );

    create table schedules (
        end_time time(6),
        has_finished boolean not null,
        recurrence_interval integer not null,
        schedule_date date,
        start_time time(6),
        id bigint generated by default as identity,
        laboratory_id bigint,
        professor_id bigint not null,
        school_year_id bigint not null,
        section_id bigint,
        semester_id bigint,
        subject_id bigint not null,
        recurrence_id uuid,
        recurrence varchar(255) check (recurrence in ('NONE','DAILY','WEEKLY')),
        remarks varchar(255),
        primary key (id)
    );

    create table school_year (
        end_year integer not null,
        start_year integer not null,
        first_semester_id bigint,
        id bigint generated by default as identity,
        second_semester_id bigint,
        summer_semester_id bigint,
        primary key (id)
    );

    create table section (
        section integer not null,
        id bigint generated by default as identity,
        program_id bigint not null,
        year varchar(255),
        primary key (id)
    );

    create table semester (
        end_date timestamp(6),
        id bigint generated by default as identity,
        start_date timestamp(6),
        name varchar(255),
        primary key (id)
    );

    create table subjects (
        id bigint generated by default as identity,
        description varchar(255),
        subject_code varchar(255),
        subject_name varchar(255),
        primary key (id)
    );

    create table token (
        is_logged_out boolean not null,
        id bigint generated by default as identity,
        user_id bigint,
        token varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        program_id bigint,
        section_id bigint,
        first_name varchar(255),
        last_name varchar(255),
        middle_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','FACULTY','STUDENT')),
        suffix varchar(255),
        user_image_path varchar(255),
        usercode varchar(255) unique,
        primary key (id)
    );

    create table visitors (
        id bigint generated by default as identity,
        visit_date timestamp(6),
        destination varchar(255),
        name varchar(255),
        other_details varchar(255),
        purpose_of_visit varchar(255),
        primary key (id)
    );

    alter table if exists attendance 
       add constraint FKkbwon00kxqwhv1cxlhpku33cn 
       foreign key (schedule_id) 
       references schedules;

    alter table if exists attendance 
       add constraint FKjcaqd29v2qy723owsdah2t8vx 
       foreign key (user_id) 
       references users;

    alter table if exists fingerprint 
       add constraint FKbe8ot0iwt05p22hdoxo0954jd 
       foreign key (user_id) 
       references users;

    alter table if exists schedule_days 
       add constraint FKfjqqji6gtqyp0e4k8ot0l7g7d 
       foreign key (schedule_id) 
       references schedules;

    alter table if exists schedules 
       add constraint FKsi14m48u6steylc2ki7dnf3c5 
       foreign key (laboratory_id) 
       references laboratory;

    alter table if exists schedules 
       add constraint FK3dsjtmjqch8chw4oucrttd6t2 
       foreign key (professor_id) 
       references users;

    alter table if exists schedules 
       add constraint FKb0a7s7n1aedgf5hcg657uv5t0 
       foreign key (school_year_id) 
       references school_year;

    alter table if exists schedules 
       add constraint FK9mhbgma6kq9bqwkfgaoeb4yr3 
       foreign key (section_id) 
       references section;

    alter table if exists schedules 
       add constraint FKkh5e9wfh635g99w8wa871ugjl 
       foreign key (semester_id) 
       references semester;

    alter table if exists schedules 
       add constraint FK7tl4569066j839d7hd28xwuw8 
       foreign key (subject_id) 
       references subjects;

    alter table if exists school_year 
       add constraint FKrpngpx3spr9t70u6gtvxr1pku 
       foreign key (first_semester_id) 
       references semester;

    alter table if exists school_year 
       add constraint FKtave5jq6dqods3rtj4md0h3dd 
       foreign key (second_semester_id) 
       references semester;

    alter table if exists school_year 
       add constraint FKhxboio9m3td3d3wurm2p4wxga 
       foreign key (summer_semester_id) 
       references semester;

    alter table if exists section 
       add constraint FKni3pe8texb73f8irwx9qdqevj 
       foreign key (program_id) 
       references program;

    alter table if exists token 
       add constraint FKj8rfw4x0wjjyibfqq566j4qng 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKip2751gaoprbkblo5w4lny6wn 
       foreign key (program_id) 
       references program;

    alter table if exists users 
       add constraint FKcaatq5ncr5ocso1oe7sxlwhcd 
       foreign key (section_id) 
       references section;

    create table attendance (
        id bigint generated by default as identity,
        schedule_id bigint not null,
        timestamp timestamp(6) not null,
        user_id bigint not null,
        status varchar(255),
        primary key (id)
    );

    create table fingerprint (
        id bigint generated by default as identity,
        section_id bigint,
        user_id bigint,
        fingerprinturl varchar(255),
        primary key (id)
    );

    create table laboratory (
        capacity integer not null,
        id bigint generated by default as identity,
        name varchar(255),
        room_code varchar(255),
        primary key (id)
    );

    create table program (
        id bigint generated by default as identity,
        program_abbreviation varchar(255),
        program_description varchar(255),
        program_name varchar(255),
        primary key (id)
    );

    create table schedule_days (
        schedule_id bigint not null,
        recurrence_days varchar(255)
    );

    create table schedules (
        end_time time(6),
        has_finished boolean not null,
        recurrence_interval integer not null,
        schedule_date date,
        start_time time(6),
        id bigint generated by default as identity,
        laboratory_id bigint,
        professor_id bigint not null,
        school_year_id bigint not null,
        section_id bigint,
        semester_id bigint,
        subject_id bigint not null,
        recurrence_id uuid,
        recurrence varchar(255) check (recurrence in ('NONE','DAILY','WEEKLY')),
        remarks varchar(255),
        primary key (id)
    );

    create table school_year (
        end_year integer not null,
        start_year integer not null,
        first_semester_id bigint,
        id bigint generated by default as identity,
        second_semester_id bigint,
        summer_semester_id bigint,
        primary key (id)
    );

    create table section (
        section integer not null,
        id bigint generated by default as identity,
        program_id bigint not null,
        year varchar(255),
        primary key (id)
    );

    create table semester (
        end_date timestamp(6),
        id bigint generated by default as identity,
        start_date timestamp(6),
        name varchar(255),
        primary key (id)
    );

    create table subjects (
        id bigint generated by default as identity,
        description varchar(255),
        subject_code varchar(255),
        subject_name varchar(255),
        primary key (id)
    );

    create table token (
        is_logged_out boolean not null,
        id bigint generated by default as identity,
        user_id bigint,
        token varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        program_id bigint,
        section_id bigint,
        first_name varchar(255),
        last_name varchar(255),
        middle_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','FACULTY','STUDENT')),
        suffix varchar(255),
        user_image_path varchar(255),
        usercode varchar(255) unique,
        primary key (id)
    );

    create table visitors (
        id bigint generated by default as identity,
        visit_date timestamp(6),
        destination varchar(255),
        name varchar(255),
        other_details varchar(255),
        purpose_of_visit varchar(255),
        primary key (id)
    );

    alter table if exists attendance 
       add constraint FKkbwon00kxqwhv1cxlhpku33cn 
       foreign key (schedule_id) 
       references schedules;

    alter table if exists attendance 
       add constraint FKjcaqd29v2qy723owsdah2t8vx 
       foreign key (user_id) 
       references users;

    alter table if exists fingerprint 
       add constraint FKbe8ot0iwt05p22hdoxo0954jd 
       foreign key (user_id) 
       references users;

    alter table if exists schedule_days 
       add constraint FKfjqqji6gtqyp0e4k8ot0l7g7d 
       foreign key (schedule_id) 
       references schedules;

    alter table if exists schedules 
       add constraint FKsi14m48u6steylc2ki7dnf3c5 
       foreign key (laboratory_id) 
       references laboratory;

    alter table if exists schedules 
       add constraint FK3dsjtmjqch8chw4oucrttd6t2 
       foreign key (professor_id) 
       references users;

    alter table if exists schedules 
       add constraint FKb0a7s7n1aedgf5hcg657uv5t0 
       foreign key (school_year_id) 
       references school_year;

    alter table if exists schedules 
       add constraint FK9mhbgma6kq9bqwkfgaoeb4yr3 
       foreign key (section_id) 
       references section;

    alter table if exists schedules 
       add constraint FKkh5e9wfh635g99w8wa871ugjl 
       foreign key (semester_id) 
       references semester;

    alter table if exists schedules 
       add constraint FK7tl4569066j839d7hd28xwuw8 
       foreign key (subject_id) 
       references subjects;

    alter table if exists school_year 
       add constraint FKrpngpx3spr9t70u6gtvxr1pku 
       foreign key (first_semester_id) 
       references semester;

    alter table if exists school_year 
       add constraint FKtave5jq6dqods3rtj4md0h3dd 
       foreign key (second_semester_id) 
       references semester;

    alter table if exists school_year 
       add constraint FKhxboio9m3td3d3wurm2p4wxga 
       foreign key (summer_semester_id) 
       references semester;

    alter table if exists section 
       add constraint FKni3pe8texb73f8irwx9qdqevj 
       foreign key (program_id) 
       references program;

    alter table if exists token 
       add constraint FKj8rfw4x0wjjyibfqq566j4qng 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKip2751gaoprbkblo5w4lny6wn 
       foreign key (program_id) 
       references program;

    alter table if exists users 
       add constraint FKcaatq5ncr5ocso1oe7sxlwhcd 
       foreign key (section_id) 
       references section;
