spring.application.name=BioSync.API
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/BioSync
spring.datasource.username=postgres
spring.datasource.password=jhean

#JPA Configs
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Credentials
app.secret.key=0a4a76f7081e0cd3b0e7d496b1e0ad4931203f18f03acb8e8731ae2d43535882 

