spring.application.name=BioSync.API
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/BioSync
spring.datasource.username=postgres
spring.datasource.password=jhean

#JPA Configs
spring.jpa.open-in-view=false

