name: Build and Deploy API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update application.properties
        run: |
          sed -i -e "s|spring.datasource.url=.*|spring.datasource.url=${{ secrets.DATABASE_URL }}|" \
                 -e "s|spring.datasource.username=.*|spring.datasource.username=${{ secrets.DATABASE_USERNAME }}|" \
                 -e "s|spring.datasource.password=.*|spring.datasource.password=${{ secrets.DATABASE_PASSWORD }}|" \
                 -e "s|app.secret.key=.*|app.secret.key=${{ secrets.AUTH_KEY }}|" \
                 -e "s|spring.mail.username=.*|spring.mail.username=${{ secrets.MAIL_USERNAME }}|" \
                 -e "s|spring.mail.password=.*|spring.mail.password=${{ secrets.MAIL_PASSWORD }}|" \
                 ./BioSync.API/src/main/resources/application.properties

      - name: Build Project
        run: mvn clean install -DskipTests
        working-directory: ./BioSync.API

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t jheankhendrick/BioSync-API ./BioSync.API

      - name: Publish Image to Docker Hub
        run: docker push jheankhendrick/bio-sync-api:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull jheankhendrick/bio-sync-api:latest

      - name: Delete Old Container
        run: docker rm -f bio-sync-api-container

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name BioSync-API jheankhendrick/bio-sync-api
