name: Deploy Web to EC2

on:
  workflow_dispatch:

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v2

    - name: Move Angular App to Root
      run: mv -f ./BioSync.UI/* .

    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm ci --legacy-peer-deps

    - name: Substitute apiUrl in app.settings
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          sed -i -e "s~apiUrl: '.*'~apiUrl: '${{ secrets.API_URL }}'~" environment/app.setting.ts
        elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
          sed -i -e "s~apiUrl: '.*'~apiUrl: '${{ secrets.API_URL_TEST }}'~" environment/app.setting.ts
        fi
      shell: /usr/bin/bash -e {0}

    - name: Substitute cryptoKey in app.settings
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          sed -i -e "s~key: '.*'~key: '${{ secrets.CRYPTO_KEY }}'~" environment/app.setting.ts
        elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
          sed -i -e "s~key: '.*'~key: '${{ secrets.CRYPTO_KEY }}'~" environment/app.setting.ts
        fi
      shell: /usr/bin/bash -e {0}

    - name: Substitute Service Uri in app.settings
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          sed -i -e "s~serviceUrl: '.*'~serviceUrl: '${{ secrets.ALLOWED_ORIGIN }}'~" environment/app.setting.ts
        elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
          sed -i -e "s~serviceUrl: '.*'~serviceUrl: '${{ secrets.ALLOWED_ORIGIN_TEST }}'~" environment/app.setting.ts
        fi
      shell: /usr/bin/bash -e {0}

    - name: Update Integration API in app.settings
      run: |
        sed -i -e "s~integrationUrl: '.*'~integrationUrl: '${{ secrets.INTEGRATION_API }}'~" environment/app.setting.ts
      shell: /usr/bin/bash -e {0}

    - name: Update Integration Key in app.settings
      run: |
        sed -i -e "s~INTEGRATION_SECRET_KEY: '.*'~INTEGRATION_SECRET_KEY: '${{ secrets.INTEGRATION_SECRET_KEY }}'~" environment/app.setting.ts
      shell: /usr/bin/bash -e {0}

    - name: Update Build Number in app.settings
      run: |
        sed -i -e "s~buildNumber: '.*'~buildNumber: '0.0.${{ github.run_number }}'~" environment/app.setting.ts
      shell: /usr/bin/bash -e {0}

    - name: Build Angular Project
      run: npm run build

    - name: Verify Build Directory
      run: ls -al dist/bio-sync.ui

    - name: Transfer Build Folder to EC2 Instance
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ 
          github.ref == 'refs/heads/main' && secrets.EC2_PRIVATE_KEY ||
          github.ref == 'refs/heads/staging' && secrets.EC2_PRIVATE_KEY_TEST }}
        REMOTE_HOST: ${{
          github.ref == 'refs/heads/main' && secrets.AWS_DEPLOY_HOST ||
          github.ref == 'refs/heads/staging' && secrets.AWS_DEPLOY_HOST_TEST }}
        REMOTE_USER: ${{ secrets.AWS_DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.AWS_DEPLOY_PORT }}
        SOURCE: "dist/bio-sync.ui/"
        TARGET: ${{ secrets.AWS_DEPLOY_TARGET }}
