name: Deploy Web to EC2

on:
  workflow_dispatch:

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v2

    - name: Move Angular App to Root
      run: mv -f ./BioSync.UI/* .

    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm ci

    # - name: Substitute variables in environment file (dev)
    #   run: |
    #        sed -i "s~apiUrl: '.*'~apiUrl: '${{ secrets.API_URL }}'~" environment/app.settings.ts

    - name: Build Angular Project
      run: npm run build

    - name: Verify Build Directory
      run: ls -al dist/bio-sync.ui

    - name: Transfer Build Folder to EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        REMOTE_HOST: 13.213.9.248
        REMOTE_USER: ubuntu
        REMOTE_PORT: 22
        SOURCE: "dist/bio-sync.ui/"
        TARGET: "/home/ubuntu/biosync"
